export const string = {
  goOutConfirmation: "Are you sure you want to go back?",
  holdOn: "Hold on!",
  cancel: "Cancel",
  yes: "Yes",
  ok: "ok",
  logOut: "LOG OUT",
  logOutMessage: "Are you want to Logout from app ?",
  tabPress: "tabPress",
  tabLongPress: "tabLongPress",
  prev: "PREV",
  next: "NEXT",
  boxing: "BOXING",
  organization: "BY TATVASOFT",
  dashboard: "DASHBOARD",
  dashboardCapitalize: "Dashboard",
  somethingWrong: "Something went wrong ! Please try again later .",
  profile: "Profile",
  savedCategory: "Saved Category",
  searchCategory: "Search categories",
  notFound: "No Data Found!",
  imageLoading: "Image is loading...",
  videoLoading: "Video is loading...",
  welcomeMessage: "Welcome Back,",
  signinContinue: "Sign in to continue",
  emailAddress: "Email Address",
  password: "Password",
  emailPlaceholder: "Enter Email Here",
  passwordPlaceholder: "Enter Password Here",
  signIn: "SIGN IN",
  loginWithFacebook: "Login with Facebook",
  loginWithGmail: "Login with Gmail",
}
