export const icons = {
  back: require("./customback.png"),
  bullet: require("./bullet.png"),
  backgroundImage: require("./layer2.png"),
  hamBurger: require("./hamburger.png"),
  home: require("./home.png"),
  profile: require("./profile.png"),
  tabactive: require("./tabactive.png"),
  tabinactive: require("./tabinactive.png"),
  logo: require("./logo.png"),
  gear: require("./gear.png"),
  handWrap: require("./handWrap.png"),
  warmUp: require("./warmUp.jpg"),
  prev: require("./prev.png"),
  prev2: require("./prev2.png"),
  next: require("./next.png"),
  gloves: require("./gloves.png"),
  activeDot: require("./activeDot.png"),
  inActiveDot: require("./inActiveDot.png"),
  mainProfile: require("./mainProfile.png"),
  search: require("./searchProfile.png"),
  downArrow: require("./downArrow.png"),
}

export type IconTypes = keyof typeof icons
