require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'BoxingProject' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'react-native-fbsdk', :path => '../node_modules/react-native-fbsdk'
  pod 'Firebase/Analytics'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  # source 'https://github.com/CocoaPods/Specs.git'
  # source 'https://cdn.cocoapods.org/'
  # source 'https://cocoapods-cdn.netlify.app/'
  # pod 'RNFastImage', :path => '../node_modules/react-native-fast-image'

  # pod 'SDWebImage', :path => '../node_modules/react-native-web-image'

  # pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  target 'BoxingProjectTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'BoxingProject-tvOS' do
  # Pods for BoxingProject-tvOS

  target 'BoxingProject-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
